[MIOpen] Asm code fix for rocm7 (#2335)
## Motivation
With last compiler version kernel build failed:
```
 /tmp/comgr-xxx/input/conv3x3wrw.s:901:22: error: redefinition of 'reverse_weights'
   reverse_weights = !reverse_weights
                     ^
/tmp/comgr-xxx/input/conv3x3wrw.s:902:21: error: redefinition of 'weights_layout'
   weights_layout = !weights_layout
```
In latest versions of clang , looks like assembler has become stricter
about symbol definitions and treating that the weights_layout is defined
twice once with default and the other with the = assignment.

## Technical Details

Added test with affected kernel configuration.
Redefinition replaced by new variable.