[SWDEV-358170][Workaround] Specify -std=c++14 to allow boost to build using latest Clang and devtoolset-7
"It's probably a bug in devtoolset-7's C++ library support for C++17 that got exposed by clang's change of its default to C++17. "

Error:
./boost/asio/detail/memory.hpp:89:15: error: no member named 'aligned_alloc' in namespace 'std'; did you mean simply 'aligned_alloc'?
  void* ptr = std::aligned_alloc(align, size);
              ^~~~~~~~~~~~~~~~~~
              aligned_alloc
/usr/include/stdlib.h:508:14: note: 'aligned_alloc' declared here
extern void *aligned_alloc (size_t __alignment, size_t __size)
             ^
1 error generated.