[MIOpen] Asm code fix and test update (#1561)
## Motivation

With last compiler version kernel build failed:
```
/tmp/comgr-xxx/input/conv1x1wrw.s:1606:21: error: redefinition of 'data_prefetch'
MIOpen Error: /xxx/src/MIOpen/src/hipoc/hipoc_program.cpp:299: Code object build failed. Source: conv1x1wrw.s
```
In latest versions of clang , looks like assembler has become stricter
about symbol definitions and treating that the data_prefetch is defined
twice once with default and the other with the = assignment.

## Technical Details

Added test with affected kernel configuration.
Redefinition replaced by new variable.

## Test Plan

mi2xx
./bin/miopen_gtest --gtest_filter=*GPU_Conv2d*AsmBwdWrw*

<!-- Explain any relevant testing done to verify this PR. -->

PASSED

<!-- Briefly summarize test outcomes. -->

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.